SELECT BK.AUTHOR_ID, AR.AUTHOR_NAME, BK.CATEGORY, 
SUM(BK.PRICE*BS.SALES) AS TOTAL_SALES
FROM BOOK BK
JOIN BOOK_SALES BS ON BK.BOOK_ID = BS.BOOK_ID
JOIN AUTHOR AR ON BK.AUTHOR_ID = AR.AUTHOR_ID
WHERE MONTH(BS.SALES_DATE) = 1
GROUP BY BK.AUTHOR_ID, BK.CATEGORY
ORDER BY BK.AUTHOR_ID ASC, BK.CATEGORY DESC;