SELECT H.HISTORY_ID, 
    CASE 
        WHEN DATEDIFF(H.END_DATE, H.START_DATE)+1>=90 THEN FLOOR(C.DAILY_FEE*(DATEDIFF(H.END_DATE, H.START_DATE) + 1)*0.9)
        WHEN DATEDIFF(H.END_DATE, H.START_DATE)+1>=30 THEN FLOOR(C.DAILY_FEE*(DATEDIFF(H.END_DATE, H.START_DATE) + 1)*0.93)
        WHEN DATEDIFF(H.END_DATE, H.START_DATE)+1>=7 THEN FLOOR(C.DAILY_FEE*(DATEDIFF(H.END_DATE, H.START_DATE) + 1)*0.95)
        ELSE FLOOR(C.DAILY_FEE*(DATEDIFF(H.END_DATE, H.START_DATE) + 1))
    END AS FEE
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H
JOIN CAR_RENTAL_COMPANY_CAR C USING (CAR_ID)
WHERE C.CAR_TYPE ='트럭'
ORDER BY FEE DESC, H.HISTORY_ID DESC;