SELECT RI.REST_ID, RI.REST_NAME, RI.FOOD_TYPE, RI.FAVORITES, RI.ADDRESS, ROUND(AVG(RR.REVIEW_SCORE),1) AS SCORE
FROM REST_INFO RI
JOIN REST_REVIEW RR USING (REST_ID)
WHERE ADDRESS LIKE '서울특별시%'
GROUP BY RI.REST_ID, RI.REST_NAME, RI.FOOD_TYPE,RI.ADDRESS, RI.FAVORITES
ORDER BY SCORE, RI.FAVORITES DESC;




-- SELECT REST_ID, REST_NAME, FOOD_TYPE, FAVORITES, ADDRESS, SCORE
-- FROM REST_INFO
-- ORDER BY SCORE, FAVORITES DESC;