SELECT RI.REST_ID, RI.REST_NAME, RI.FOOD_TYPE, RI.FAVORITES, RI.ADDRESS, RR.SCORE
FROM REST_INFO RI
JOIN (
    SELECT REST_ID, ROUND(AVG(REVIEW_SCORE), 1) AS SCORE
    FROM REST_REVIEW
    GROUP BY REST_ID
) RR USING (REST_ID)
WHERE RI.ADDRESS LIKE '서울특별시%'
ORDER BY SCORE, RI.FAVORITES DESC;



-- SELECT REST_ID, REST_NAME, FOOD_TYPE, FAVORITES, ADDRESS, SCORE
-- FROM REST_INFO
-- ORDER BY SCORE, FAVORITES DESC;