SELECT DISTINCT C.CAR_ID, C.CAR_TYPE, FLOOR(C.DAILY_FEE*30*(100-P.DISCOUNT_RATE)/100) AS FEE
FROM CAR_RENTAL_COMPANY_CAR C
LEFT JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY H ON C.CAR_ID = H.CAR_ID
JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P ON C.CAR_TYPE = P.CAR_TYPE AND DURATION_TYPE = '30일 이상'
WHERE (C.CAR_TYPE = '세단' OR C.CAR_TYPE = 'SUV') AND (H.START_DATE>'2022-11-30' OR H.END_DATE<'2022-11-01')
OR HISTORY_ID IS NULL
HAVING FEE>=500000 AND FEE<=2000000
ORDER BY FEE DESC, CAR_TYPE, CAR_ID DESC;