SELECT YEAR(OS.SALES_DATE) YEAR, MONTH(OS.SALES_DATE) MONTH, UI.GENDER, COUNT(DISTINCT UI.USER_ID) AS USERS
FROM ONLINE_SALE OS
JOIN USER_INFO UI USING (USER_ID)
WHERE UI.GENDER IS NOT NULL
GROUP BY YEAR, MONTH, UI.GENDER
ORDER BY  YEAR, MONTH, GENDER;