WITH RECURSIVE TIME_TABLE AS(
    SELECT 0 AS HOUR
    UNION ALL
    SELECT HOUR+1 AS HOUR FROM TIME_TABLE WHERE HOUR<23
)

SELECT T.HOUR, COUNT(HOUR(AO.DATETIME)) AS COUNT
FROM ANIMAL_OUTS AO
RIGHT JOIN TIME_TABLE T ON T.HOUR = HOUR(AO.DATETIME)
GROUP BY T.HOUR;