SELECT MP.MEMBER_NAME, RR.REVIEW_TEXT, RR.REVIEW_DATE
FROM MEMBER_PROFILE MP
JOIN REST_REVIEW RR USING (MEMBER_ID)
WHERE MP.MEMBER_ID = (SELECT MEMBER_ID 
FROM MEMBER_PROFILE MP
JOIN REST_REVIEW RR USING (MEMBER_ID)
GROUP BY MEMBER_ID
ORDER BY COUNT(REVIEW_ID) DESC
LIMIT 1)
ORDER BY  RR.REVIEW_DATE,RR.REVIEW_TEXT;

