SELECT I.REST_ID
    , I.REST_NAME
    , I.FOOD_TYPE
    , I.FAVORITES
    , I.ADDRESS
    , ROUND(AVG(R.REVIEW_SCORE),2) as score
FROM REST_INFO  I, REST_REVIEW R
WHERE I.ADDRESS Like '서울%' and R.REST_ID = I.REST_ID 
GROUP BY I.REST_ID, I.REST_NAME, I.FOOD_TYPE, I.FAVORITES, I.ADDRESS
ORDER BY score DESC, I.FAVORITES DESC