SELECT HE.EMP_NO, HE.EMP_NAME,	
CASE WHEN HG.SCORE>=96 THEN 'S'
    WHEN HG.SCORE>=90 THEN 'A'
    WHEN HG.SCORE>=80 THEN 'B'
    ELSE 'C'
END AS GRADE, 
CASE WHEN HG.SCORE>=96 THEN SAL*0.2
    WHEN HG.SCORE>=90 THEN SAL*0.15
    WHEN HG.SCORE>=80 THEN SAL*0.1
    ELSE 0
END AS BONUS
FROM HR_EMPLOYEES HE
JOIN (SELECT EMP_NO, AVG(SCORE) AS SCORE FROM HR_GRADE GROUP BY EMP_NO) HG USING (EMP_NO)
ORDER BY HE.EMP_NO;
