SELECT COUNT(F.FISH_TYPE) AS FISH_COUNT, Fn.FISH_NAME AS FISH_NAME
FROM FISH_INFO F, FISH_NAME_INFO Fn
WHERE F.FISH_TYPE = Fn.FISH_TYPE
GROUP BY F.FISH_TYPE,Fn.FISH_NAME
ORDER BY COUNT(F.FISH_TYPE) DESC