-- 코드를 작성해주세요
WITH RECURSIVE ECOLI_GEN AS (
    SELECT ID, PARENT_ID, 1 AS GENERATION
    FROM ECOLI_DATA 
    WHERE PARENT_ID IS NULL 

    UNION ALL 
    
    SELECT ED.ID, ED.PARENT_ID, EG.GENERATION+1
    FROM ECOLI_DATA ED
    JOIN ECOLI_GEN  EG ON EG.ID = ED.PARENT_ID
)


SELECT COUNT(GENERATION) AS COUNT, GENERATION
FROM ECOLI_GEN EG
# WHERE ID NOT IN (SELECT PARENT_ID FROM ECOLI_GEN WHERE PARENT_ID IS NOT NULL)
WHERE NOT EXISTS (SELECT * FROM ECOLI_GEN T WHERE EG.ID = T.PARENT_ID)
GROUP BY GENERATION
ORDER  BY GENERATION;