-- 코드를 입력하세요
SELECT FR.PRODUCT_ID, FR.PRODUCT_NAME, SUM(FR.PRICE*FO.AMOUNT) AS TOTAL_SALES
FROM FOOD_PRODUCT FR
JOIN FOOD_ORDER FO USING (PRODUCT_ID)
WHERE DATE_FORMAT(FO.PRODUCE_DATE, '%Y-%m')='2022-05'
GROUP BY FR.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, PRODUCT_ID ASC;
