WITH RECURSIVE GEN_TABLE AS (
    SELECT ID, PARENT_ID, 1 AS GENERATION FROM ECOLI_DATA WHERE PARENT_ID IS NULL 
    UNION ALL
    SELECT ED.ID, ED.PARENT_ID, GT.GENERATION+1
    FROM  ECOLI_DATA ED
    JOIN  GEN_TABLE GT ON GT.ID = ED.PARENT_ID
)

SELECT COUNT(GT.ID) AS COUNT, GENERATION
FROM GEN_TABLE GT
LEFT JOIN ECOLI_DATA ED ON GT.ID = ED.PARENT_ID
WHERE ED.ID IS NULL
GROUP BY GENERATION
ORDER BY GENERATION;