-- 코드를 입력하세요
SELECT J.FLAVOR
FROM (
    SELECT FLAVOR, SUM(TOTAL_ORDER) AS TOTAL_ORDER
    FROM JULY
    GROUP BY FLAVOR
) J
JOIN FIRST_HALF FH USING (FLAVOR)
ORDER BY J.TOTAL_ORDER+FH.TOTAL_ORDER DESC 
LIMIT 3;