-- 코드를 입력하세요
WITH RECURSIVE TIME_CTE AS (
    SELECT 0 AS HOUR
    UNION ALL
    SELECT HOUR + 1 FROM TIME_CTE WHERE HOUR < 23
)

SELECT 
    TIME_CTE.HOUR, 
    COUNT(ANIMAL_OUTS.DATETIME) AS COUNT
FROM TIME_CTE
LEFT JOIN ANIMAL_OUTS 
    ON TIME_CTE.HOUR = HOUR(ANIMAL_OUTS.DATETIME)
GROUP BY TIME_CTE.HOUR
ORDER BY TIME_CTE.HOUR;