SELECT A.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY, SUM(B.PRICE *BS.SALES) AS TOTAL_SALES
FROM BOOK B
JOIN AUTHOR A USING (AUTHOR_ID)
JOIN BOOK_SALES BS USING (BOOK_ID)
WHERE DATE_FORMAT(BS.SALES_DATE,'%Y-%m') = '2022-01'
GROUP BY  A.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY
ORDER BY AUTHOR_ID, CATEGORY DESC;