-- 코드를 입력하세요


SELECT P.MEMBER_NAME, R.REVIEW_TEXT, R.REVIEW_DATE
FROM REST_REVIEW R
JOIN MEMBER_PROFILE P USING(MEMBER_ID)
WHERE MEMBER_ID = (
    SELECT MEMBER_ID
    FROM REST_REVIEW 
    JOIN MEMBER_PROFILE P USING(MEMBER_ID)
    GROUP BY MEMBER_ID
    ORDER BY SUM(REVIEW_SCORE) DESC
    LIMIT 1)
ORDER BY R.REVIEW_DATE,R.REVIEW_TEXT;
