-- 코드를 작성해주세요

SELECT
    YEAR(E.DIFFERENTIATION_DATE) AS YEAR,
    D.NUM - E.SIZE_OF_COLONY AS YEAR_DEV,
    E.ID
FROM ECOLI_DATA E
JOIN (
    SELECT
        YEAR(DIFFERENTIATION_DATE) AS YEAR,
        MAX(SIZE_OF_COLONY) AS NUM
    FROM ECOLI_DATA
    GROUP BY YEAR(DIFFERENTIATION_DATE)
) D
ON YEAR(E.DIFFERENTIATION_DATE) = D.YEAR
ORDER BY YEAR, YEAR_DEV;