SELECT FI.ID, FN.FISH_NAME, FI.LENGTH
FROM FISH_INFO FI
JOIN FISH_NAME_INFO FN USING (FISH_TYPE)
WHERE (FI.FISH_TYPE, FI.LENGTH) IN  (
    SELECT FN.FISH_TYPE, MAX(FI.LENGTH) AS LENGTH 
    FROM FISH_INFO FI
    JOIN FISH_NAME_INFO FN USING (FISH_TYPE)
    GROUP BY FN.FISH_TYPE
    )
ORDER BY FI.ID;
 
