SELECT B.CATEGORY, SUM(BS.SALES) AS TOTAL_SALES
FROM BOOK B
JOIN (SELECT BOOK_ID, SUM(SALES) AS SALES
FROM BOOK_SALES
WHERE DATE_FORMAT(SALES_DATE,'%Y-%m') = '2022-01'
GROUP BY BOOK_ID) BS USING (BOOK_ID)
GROUP BY B.CATEGORY
ORDER BY B.CATEGORY;